

//N wall, top strip
polygon {
	4

	<-4, 0.8, 12>
	<5, 0.8, 12>
	<5, 1.0, 12>
	<-4, 1.0, 12>

	pigment { color Gray75 }
}

//N wall, left side
polygon {
	4

	<-4, 0.0, 12>
	<0, 0.0, 12>
	<0, 1.0, 12>
	<-4, 1.0, 12>

	pigment { color Gray95 }
}

//N wall, right side
polygon {
	4

	<1, 0.0, 12>
	<5, 0.0, 12>
	<5, 1.0, 12>
	<1, 1.0, 12>

	pigment { color Gray95 }
}
//E wall, top strip
polygon {
	4

	<12, 0.8, -4>
	<12, 0.8, 5>
	<12, 1.0, 5>
	<12, 1.0, -4>

	pigment { color Gray75 }
}

//E wall, south side
polygon {
	4

	<12, 0.0, -4>
	<12, 0.0, 0>
	<12, 1.0, 0>
	<12, 1.0, -4>

	pigment { color Gray95 }
}

//E wall, north side
polygon {
	4

	<12, 0.0, 1>
	<12, 0.0, 5>
	<12, 1.0, 5>
	<12, 1.0, 1>

	pigment { color Gray95 }
}

//NE wall
polygon {
	4

	<5, 0.0, 12>
	<5, 1.0, 12>
	<12, 1.0, 5>
	<12, 0.0, 5>

	pigment { color Gray95 }
}

//NW wall
polygon {
	4

	<-4, 0.0, 12>
	<-4, 1.0, 12>
	<-11, 1.0, 5>
	<-11, 0.0, 5>

	pigment { color Gray95 }
}
//SW wall
polygon {
	4

	<-4, 0.0, -11>
	<-4, 1.0, -11>
	<-11, 1.0, -4>
	<-11, 0.0, -4>

	pigment { color Gray95 }
}
//SE wall
polygon {
	4

	<5, 0.0, -11>
	<5, 1.0, -11>
	<12, 1.0, -4>
	<12, 0.0, -4>

	pigment { color Gray95 }
}

//W wall, top strip
polygon {
	4

	<-11, 0.8, -4>
	<-11, 0.8, 5>
	<-11, 1.0, 5>
	<-11, 1.0, -4>

	pigment { color Gray75 }
}

//W wall, north side
polygon {
	4

	<-11, 0.0, 1>
	<-11, 0.0, 5>
	<-11, 1.0, 5>
	<-11, 1.0, 1>

	pigment { color Gray95 }
}
//W wall, south side
polygon {
	4

	<-11, 0.0, 0>
	<-11, 0.0, -4>
	<-11, 1.0, -4>
	<-11, 1.0, 0>

	pigment { color Gray95 }
}

//S wall, top strip
polygon {
	4

	<-4, 0.8, -11>
	<5, 0.8, -11>
	<5, 1.0, -11>
	<-4, 1.0, -11>

	pigment { color Gray75 }
}

//S wall, left side
polygon {
	4

	<-4, 0.0, -11>
	<0, 0.0, -11>
	<0, 1.0, -11>
	<-4, 1.0, -11>

	pigment { color Gray95 }
}

//S wall, right side
polygon {
	4

	<1, 0.0, -11>
	<5, 0.0, -11>
	<5, 1.0, -11>
	<1, 1.0, -11>

	pigment { color Gray95 }
}

