

//entry
box { <3, 0, 2>, <4, 1, 3> pigment { color Gray95 } }
box { <3, 0, 6>, <4, 1, 7> pigment { color Gray95 } }

box { <2, 0, 3>, <5, 3, 6> pigment { color Gray95 } }


//watchtowers
box { <2, 3, 3>, <3, 4, 4> pigment { color Gray95 } }
box { <2, 3, 5>, <3, 4, 6> pigment { color Gray95 } }
box { <4, 3, 3>, <5, 4, 4> pigment { color Gray95 } }
box { <4, 3, 5>, <5, 4, 6> pigment { color Gray95 } }

box { <3, 3, 4>, <4, 5, 5> pigment { color Gray95 } }


