

//W wall
polygon {
	4

	<1, 0, 1>
	<1, 0, 5>
	<1, 0.75, 5>
	<1, 0.85, 1>

	pigment { color Gray95 }
}

//S wall, W side
polygon {
	4

	<1, 0, 1>
	<3, 0, 1>
	<3, 0.75, 1>
	<1, 0.85, 1>

	pigment { color Gray95 }
}
//S wall, E side
polygon {
	4

	<4, 0, 1>
	<6, 0, 1>
	<6, 0.85, 1>
	<4, 0.75, 1>

	pigment { color Gray95 }
}

//E wall
polygon {
	4

	<6, 0, 1>
	<6, 0, 4>
	<6, 0.85, 4>
	<6, 0.85, 1>

	pigment { color Gray95 }
}

