
box { <-1.1, 0, -12>, <-0.9, 0.05, 12> pigment { color White } }
box { <-2.1, 0, -12>, <-1.9, 0.05, 12> pigment { color White } }
box { <-3.1, 0, -12>, <-2.9, 0.05, 12> pigment { color White } }
box { <-4.1, 0, -12>, <-3.9, 0.05, 12> pigment { color White } }
box { <-5.1, 0, -12>, <-4.9, 0.05, 12> pigment { color White } }
box { <-6.1, 0, -12>, <-5.9, 0.05, 12> pigment { color White } }
box { <-7.1, 0, -12>, <-6.9, 0.05, 12> pigment { color White } }
box { <-8.1, 0, -12>, <-7.9, 0.05, 12> pigment { color White } }
box { <-9.1, 0, -12>, <-8.9, 0.05, 12> pigment { color White } }
box { <-10.1, 0, -12>, <-9.9, 0.05, 12> pigment { color White } }
box { <-11.1, 0, -12>, <-10.9, 0.05, 12> pigment { color White } }
box { <-12.1, 0, -12>, <-11.9, 0.05, 12> pigment { color White } }

box { <-0.1, 0, -12>, <0.1, 0.05, 12> pigment { color White } }
box { <0.9, 0, -12>, <1.1, 0.05, 12> pigment { color White } }
box { <1.9, 0, -12>, <2.1, 0.05, 12> pigment { color White } }
box { <2.9, 0, -12>, <3.1, 0.05, 12> pigment { color White } }
box { <3.9, 0, -12>, <4.1, 0.05, 12> pigment { color White } }
box { <4.9, 0, -12>, <5.1, 0.05, 12> pigment { color White } }
box { <5.9, 0, -12>, <6.1, 0.05, 12> pigment { color White } }
box { <6.9, 0, -12>, <7.1, 0.05, 12> pigment { color White } }
box { <7.9, 0, -12>, <8.1, 0.05, 12> pigment { color White } }
box { <8.9, 0, -12>, <9.1, 0.05, 12> pigment { color White } }
box { <9.9, 0, -12>, <10.1, 0.05, 12> pigment { color White } }
box { <10.9, 0, -12>, <11.1, 0.05, 12> pigment { color White } }
box { <11.9, 0, -12>, <12.1, 0.05, 12> pigment { color White } }

box { <-12, 0, -0.1>, <12, 0.05, 0.1> pigment { color White } }
box { <-12, 0, 0.9>, <12, 0.05, 1.1> pigment { color White } }
box { <-12, 0, 1.9>, <12, 0.05, 2.1> pigment { color White } }
box { <-12, 0, 2.9>, <12, 0.05, 3.1> pigment { color White } }
box { <-12, 0, 3.9>, <12, 0.05, 4.1> pigment { color White } }
box { <-12, 0, 4.9>, <12, 0.05, 5.1> pigment { color White } }
box { <-12, 0, 5.9>, <12, 0.05, 6.1> pigment { color White } }
box { <-12, 0, 6.9>, <12, 0.05, 7.1> pigment { color White } }
box { <-12, 0, 7.9>, <12, 0.05, 8.1> pigment { color White } }
box { <-12, 0, 8.9>, <12, 0.05, 9.1> pigment { color White } }
box { <-12, 0, 9.9>, <12, 0.05, 10.1> pigment { color White } }
box { <-12, 0, 10.9>, <12, 0.05, 11.1> pigment { color White } }
box { <-12, 0, 11.9>, <12, 0.05, 12.1> pigment { color White } }

box { <-12, 0, -0.9>, <12, 0.05, -1.1> pigment { color White } }
box { <-12, 0, -1.9>, <12, 0.05, -2.1> pigment { color White } }
box { <-12, 0, -2.9>, <12, 0.05, -3.1> pigment { color White } }
box { <-12, 0, -3.9>, <12, 0.05, -4.1> pigment { color White } }
box { <-12, 0, -4.9>, <12, 0.05, -5.1> pigment { color White } }
box { <-12, 0, -5.9>, <12, 0.05, -6.1> pigment { color White } }
box { <-12, 0, -6.9>, <12, 0.05, -7.1> pigment { color White } }
box { <-12, 0, -7.9>, <12, 0.05, -8.1> pigment { color White } }
box { <-12, 0, -8.9>, <12, 0.05, -9.1> pigment { color White } }
box { <-12, 0, -9.9>, <12, 0.05, -10.1> pigment { color White } }
box { <-12, 0, -10.9>, <12, 0.05, -11.1> pigment { color White } }
box { <-12, 0, -11.9>, <12, 0.05, -12.1> pigment { color White } }


