

//Posts
box { <1.1, 0, -0.05>, <1.2, 0.62, -0.10> pigment { colour MediumWood } }
box { <1.5, 0, -0.05>, <1.6, 0.62, -0.10> pigment { colour MediumWood } }
box { <1.8, 0, -0.05>, <1.9, 0.62, -0.10> pigment { colour MediumWood } }
box { <2.3, 0, -0.05>, <2.4, 0.62, -0.10> pigment { colour MediumWood } }
box { <2.7, 0, -0.05>, <2.8, 0.62, -0.10> pigment { colour MediumWood } }

box { <4.2, 0, -0.05>, <4.3, 0.62, -0.10> pigment { colour MediumWood } }
box { <4.7, 0, -0.05>, <4.8, 0.62, -0.10> pigment { colour MediumWood } }
box { <5.1, 0, -0.05>, <5.2, 0.62, -0.10> pigment { colour MediumWood } }
box { <5.5, 0, -0.05>, <5.6, 0.62, -0.10> pigment { colour MediumWood } }

//Rails

box { <1.02, 0.49, -0.01>, <2.02, 0.59, -0.05> pigment { colour MediumWood } }
box { <1.01, 0.25, -0.01>, <2.00, 0.35, -0.05> pigment { colour MediumWood } }

box { <2.01, 0.37, -0.01>, <3.03, 0.47, -0.05> pigment { colour MediumWood } }
box { <1.98, 0.12, -0.01>, <3.04, 0.22, -0.05> pigment { colour MediumWood } }

